config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # S T A G E S
  post "/sessions/:uuid/start_game", to: "game_sessions#start_game", as: :start_game
  get "/sessions/:uuid/advance_stage/:stage", to: "game_sessions#advance_stage_handler", as: :advance_stage

  # S T A R T
  # Stage 0 - Host Welcome Page
  root to: "pages#welcome"
  # Stage 0 - Host Create Session
  post "/sessions", to: "game_sessions#create", as: :create_session

  # J O I N I N G
  # Stage 1 - Host Green Room
  get  "/sessions/:uuid", to: "game_sessions#show", as: :green_room_host
  # Stage 1 - Guest Green Room / Join Game Session
  get "/sessions/:uuid/guests/new", to: "guests#new", as: :new_guest
  post "/sessions/:uuid/guests", to: "guests#create", as: :create_guest
  get "/sessions/:uuid/green_room", to: "game_sessions#green_room", as: :green_room_guest

  # G E N R E
  # Stage 2 - Host+Guest Genre Intro
  get "/sessions/:uuid/genre_start", to: "game_sessions#genre_start", as: :genre_start
  # Stage 3 - Guest Genre Voting
  get "/sessions/:uuid/genre_votes/new", to: "genre_votes#new", as: :new_genre_votes
  post "/sessions/:uuid/genre_votes", to: "genre_votes#create", as: :game_session_genre_votes
  get "/sessions/:uuid/genre_votes/:id", to: "genre_votes#show", as: :genre_vote
  get "/sessions/:uuid/genre_stats", to: "game_sessions#genre_stats", as: :genre_stats
  # Stage 3.5 - Guest Genre Result
  get "/sessions/:uuid/genre_result", to: "game_sessions#genre_result", as: :genre_result

  # S O N G
  # Stage 4 - Host+Guest Song Intro
  get "/sessions/:uuid/song_start", to: "game_sessions#song_start", as: :song_start
  # Stage 5 - Guest Song Voting
  get "/sessions/:uuid/song_votes/new", to: "song_votes#new", as: :new_song_votes
  post "/sessions/:uuid/song_votes", to: "song_votes#create", as: :create_song_votes
  get "/sessions/:uuid/song_stats", to: "game_sessions#song_stats", as: :song_stats
  # Stage 55 - Guest Song Result
  get "/sessions/:uuid/song_result", to: "game_sessions#song_result", as: :song_result

  # S I N G I N G
  # Stage 6 - Host+Guest Sing Intro
  get "/sessions/:uuid/sing_start", to: "game_sessions#sing_start", as: :sing_start
  # Stage 8 - Host+Guest Sing Outro
  get "/sessions/:uuid/sing_end", to: "game_sessions#sing_end", as: :sing_end

end

app/models/genre_vote.rb
class GenreVote < ApplicationRecord
  belongs_to :guest
  belongs_to :genre

  validates :guest_id, uniqueness: true

  after_create_commit :broadcast_message

  private

  def broadcast_message
    broadcast_append_to "genre_stats_for_#{guest.game_session.id}",
                        partial: "game_sessions/genre_chart_stat",
                        target: "stats",
                        locals: { session: guest.game_session }
  end

end

app/controllers/genre_votes_controller.rb
class GenreVotesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_session
  before_action :verify_host_or_guest
  before_action :prevent_double_voting, only: [:new, :create]

  def new
    @genre_vote = GenreVote.new
  end

  def create
    @genre_vote = GenreVote.new(genre_vote_params)
    @genre_vote.guest = current_guest_for_session

    if @genre_vote.save
      redirect_to genre_vote_path(@session.uuid, @genre_vote)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
     @genre_vote = GenreVote.find(params[:id])
  end

  private

  def genre_vote_params
    params.require(:genre_vote).permit(:genre_id)
  end

  def set_session
    @session = GameSession.find_by!(uuid: params[:uuid])
  end

  def prevent_double_voting
    @existing_genre_vote = GenreVote.find_by(guest: current_guest_for_session)
    redirect_to genre_vote_path(@session.uuid, @existing_genre_vote) if @existing_genre_vote
  end

end

app/views/genre_votes/new.html.erb
<!--
  GUEST
  STAGE 3
  get "/sessions/:uuid/genre_votes/new", to: "genre_votes#new", as: :new_genre_votes
  post "/sessions/:uuid/genre_votes", to: "genre_votes#create", as: :create_genre_votes
  # genre voting, different views for host and guest
  # previous page: ../game_sessions/genre_start.html.erb
  # next page: ../game_sessions/genre_result.html.erb
 -->

<%= turbo_stream_from "game_session_#{@session.uuid}_guest" if current_guest_for_session %>


<div class="container">

  <h1>What’s your jam? 🎧</h1>

    <%= simple_form_for [@session.uuid, @genre_vote], url: game_session_genre_votes_path(@session.uuid, @genre_vote), html: { data: { controller: "form-submission" }} do |f| %>
      <div class="row">
        <div class="col">
          <%= f.association :genre , legend_tag: false,
                      as: :radio_buttons,
                      collection: Genre.all,
                      collection_wrapper_tag: 'div',
                      item_wrapper_class: 'category-item',
                      input_html: {class: 'category-selector',
                      data: { action: "change->form-submission#submit" }}
                      %>

        </div>
      </div>
    <% end %>

  <h1><span id="countdown-20"></span></h1>

</div>

  <%# <%= render 'shared/debug_stage_nav' %>

app/views/genre_votes/show.html.erb
<!--
  GUEST
  STAGE 3
  # shows selected genre for guest
  # previous page: new.html.erb
  # next page:
 -->

<%= turbo_stream_from "game_session_#{@session.uuid}_guest" if current_guest_for_session %>


<div class="container">

  <p>You just added some serious flavor to the mix.</p>
  <h1><span style="color: #FAEF5D; font-weight: bold;"><%= @genre_vote.genre.name %></span></h1>
  <p>
    Wanna see how your taste stacks up? Check the big screen for the crowd’s vibe check.
  </p>

</div>